### ISSUE TITLE
Messages not being received from Tappy

### ISSUE THREAD

**Issue by i-koda** [debugerr/TappyBleBridge#1]
Messages are not being received from the Tappy when using the TappyBleBridge and Wrapper as documented.

Based on debugging, I believe the cause of the issue is that the setupNotifications() function is not being called by either the wrapper or the bridge code therefore there are no ble notifications received.

When communicator.setupNotifications() is explicitly called, the notification messages start working as expected.

I'm not sure whether this should be called just once upon successful connection or it should be called each time the notification subscribers are changed.  Either way, shouldn't this be called from the code for the respective handler function(s)?

Apologies if my explanation is not entirely clear.  This API and ble communications is new to me and I am still developing my understanding.

**Comment by p-schuler** [comment]
setupNotifications() has to be called once before starting to listen to NDEF messages (after you established a connection). I updated the readme with a sample.
